name: Check Latest Files

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual runs

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run file checker
        run: npm test
        # If you want to use environment variables instead of config.js:
        # env:
        #   FTP_HOST: ${{ secrets.FTP_HOST }}
        #   FTP_USER: ${{ secrets.FTP_USER }}
        #   FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} 